// <auto-generated />
using System;
using LiftBattery.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiftBattery.Api.Data.Migrations
{
    [DbContext(typeof(LiftBatteryDbContext))]
    [Migration("20260627035016_AddBetaUsersAndAuthSessions")]
    partial class AddBetaUsersAndAuthSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.AuthSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_AuthSessions_TokenHash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("IX_AuthSessions_UserId_ExpiresAtUtc");

                    b.ToTable("AuthSessions", (string)null);
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.PreCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Motivation")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PreCheckDate")
                        .HasColumnType("date");

                    b.Property<int>("PreviousSessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PreviousSessionRpe")
                        .HasColumnType("int");

                    b.Property<int>("RestingHeartRateDelta")
                        .HasColumnType("int");

                    b.Property<decimal>("SleepHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Soreness")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PreCheckDate")
                        .IsUnique()
                        .HasDatabaseName("UX_PreChecks_UserId_PreCheckDate");

                    b.ToTable("PreChecks", (string)null);
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_TrainingDays_UserId_Date");

                    b.ToTable("TrainingDays", (string)null);
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("int");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId", "ExerciseOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_TrainingExercises_TrainingSessionId_ExerciseId");

                    b.ToTable("TrainingExercises", (string)null);
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("SessionRpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainingDayId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingDayId", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("UX_TrainingSessions_TrainingDayId_StartTime");

                    b.ToTable("TrainingSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrainingSessions_DurationMinutes", "[DurationMinutes] > 0");

                            t.HasCheckConstraint("CK_TrainingSessions_SessionRpe", "[SessionRpe] >= 0 AND [SessionRpe] <= 10");
                        });
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsWarmUp")
                        .HasColumnType("bit");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rir")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("SetOrder")
                        .HasColumnType("int");

                    b.Property<int>("TrainingExerciseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingExerciseId", "SetOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_TrainingSets_TrainingExerciseId_SetOrder");

                    b.ToTable("TrainingSets", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrainingSets_Reps", "[Reps] >= 0");

                            t.HasCheckConstraint("CK_TrainingSets_Rir", "[Rir] IS NULL OR ([Rir] >= 0 AND [Rir] <= 10)");

                            t.HasCheckConstraint("CK_TrainingSets_Rpe", "[Rpe] IS NULL OR ([Rpe] >= 0 AND [Rpe] <= 10)");

                            t.HasCheckConstraint("CK_TrainingSets_SetOrder", "[SetOrder] > 0");

                            t.HasCheckConstraint("CK_TrainingSets_WeightKg", "[WeightKg] >= 0");
                        });
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PreferredUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TrainingGoal")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("WeeklyTargetTrainingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_PreferredUnit", "[PreferredUnit] IN ('kg', 'lb')");

                            t.HasCheckConstraint("CK_Users_WeeklyTargetTrainingDays", "[WeeklyTargetTrainingDays] >= 1 AND [WeeklyTargetTrainingDays] <= 14");
                        });
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.AuthSession", b =>
                {
                    b.HasOne("LiftBattery.Api.Data.Entities.User", "User")
                        .WithMany("AuthSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.PreCheck", b =>
                {
                    b.HasOne("LiftBattery.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingDay", b =>
                {
                    b.HasOne("LiftBattery.Api.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingExercise", b =>
                {
                    b.HasOne("LiftBattery.Api.Data.Entities.Training.TrainingSession", "TrainingSession")
                        .WithMany("Exercises")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingSession", b =>
                {
                    b.HasOne("LiftBattery.Api.Data.Entities.Training.TrainingDay", "TrainingDay")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainingDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingDay");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingSet", b =>
                {
                    b.HasOne("LiftBattery.Api.Data.Entities.Training.TrainingExercise", "TrainingExercise")
                        .WithMany("Sets")
                        .HasForeignKey("TrainingExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingExercise");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingDay", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.Training.TrainingSession", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.User", b =>
                {
                    b.Navigation("AuthSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
